a = ("oof")

for i in range (300):
    
    print ((a) .center(29))
    print ((a) .center(27))
    print ((a) .center(25))
    print ((a) .center(23))
    print ((a) .center(21))
    print ((a) .center(19))
    print ((a) .center(17))
    print ((a) .center(15))
    print ((a) .center(13))
    print ((a) .center(11))
    print ((a) .center(9))
    print ((a) .center(7))
    print ((a) .center(9))
    print ((a) .center(11))
    print ((a) .center(13))
    print ((a) .center(15))
    print ((a) .center(17))
    print ((a) .center(19))
    print ((a) .center(21))
    print ((a) .center(23))
    print ((a) .center(25))
    print ((a) .center(27))
    print ((a) .center(29))
