#Andy Chan
#Code Practice 1
#September 7th, 2018

print ("")
print ("Hello World")
print ("")

print ("Hello World " *1000)
print ("")

print ("Hello World" .center(80) *80)
print ("")

print ("Hello World" .center(80) + "Andy")
print ("")


a="Welcome"


print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))


print ("")
print ("A" .center(20)+"B" .center(20)+"C" .center(40))
print ("A" .rjust(20)+"B" .center(20)+"C" .ljust(40))
print ("I" .center(40)+"Love This!" .center(40))
print ("")


print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))

print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World" .center(80) *80)
print ("")
print ("Hello World " *1000)
print ("")
print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")


print ("Hello World " *1000)
print ("")

print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))

print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))

print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))
print ((a) .center(7))
print ((a) .center(9))
print ((a) .center(11))
print ((a) .center(13))
print ((a) .center(15))
print ((a) .center(17))
print ((a) .center(19))
print ((a) .center(21))
print ((a) .center(23))
print ((a) .center(25))
print ((a) .center(27))
print ((a) .center(29))
print ((a) .center(27))
print ((a) .center(25))
print ((a) .center(23))
print ((a) .center(21))
print ((a) .center(19))
print ((a) .center(17))
print ((a) .center(15))
print ((a) .center(13))
print ((a) .center(11))
print ((a) .center(9))
print ((a) .center(7))


